spring:
  datasource:
    url: 'jdbc:h2:file:./target/database/h2'
    #url: jdbc:h2:mem:test_mem
    username: sa
    password: null
    driverClassName: org.h2.Driver
    max-active: 30

  batch:
    job:
      enabled: false

hapi:
  fhir:
    ### enable to set the Server URL
    #    server_address: http://hapi.fhir.org/baseR4
    ### This is the FHIR version. Choose between, DSTU2, DSTU3, R4 or R5
    fhir_version: DSTU3

    tester:

      home:
        name: Local Tester
        server_address: 'http://127.0.0.1:8183/STU3'
        refuse_to_fetch_third_party_urls: false
        fhir_version: DSTU3

      global:
        name: Global Tester
        server_address: "http://hapi.fhir.unisa/STU3"
        refuse_to_fetch_third_party_urls: false
        fhir_version: DSTU3
